name: front
description: Aplicación de ventas Flutter

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"  # Usa comillas y especifica rango

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0  # Añade esto para llamadas API
  provider: ^6.0.3  # Para gestión de estado
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.3  # Para arquitectura BLoC (opcional pero recomendado)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.4  # Para generación de código

flutter:
  uses-material-design: true